name: CI Build Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple script
        run: |
          echo "Hello from GitHub Actions!"
          # Uncomment this line to force a failure:
          # exit 1
